<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>eu.jbeernink</groupId>
	<artifactId>hypospray</artifactId>
	<version>${revision}</version>
	<packaging>pom</packaging>
	<modules>
		<module>annotation</module>
		<module>codegeneration</module>
		<module>compile</module>
		<module>core</module>
		<module>demo</module>
		<module>discovery</module>
		<module>docs</module>
		<module>integration</module>
		<module>lite</module>
		<module>scope</module>
		<module>testing</module>
		<module>util</module>
		<module>xml</module>
		<module>event</module>
		<module>model</module>
		<module>invoker</module>
	</modules>

	<distributionManagement>
		<repository>
			<id>github</id>
			<name>GitHub Packages</name>
			<url>https://maven.pkg.github.com/janbeernink/hypospray</url>
		</repository>
	</distributionManagement>

	<properties>
		<maven.compiler.release>25</maven.compiler.release>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<revision>0.1-SNAPSHOT</revision>
		<cdi.version>4.1.0</cdi.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.junit</groupId>
				<artifactId>junit-bom</artifactId>
				<version>6.1.3</version>
				<scope>import</scope>
				<type>pom</type>
			</dependency>

			<dependency>
				<groupId>jakarta.enterprise</groupId>
				<artifactId>jakarta.enterprise.cdi-api</artifactId>
				<version>${cdi.version}</version>
			</dependency>

			<dependency>
				<groupId>jakarta.enterprise</groupId>
				<artifactId>cdi-tck-lang-model</artifactId>
				<version>${cdi.version}</version>
			</dependency>

			<dependency>
				<groupId>org.jspecify</groupId>
				<artifactId>jspecify</artifactId>
				<version>1.0.1</version>
			</dependency>

		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>flatten-maven-plugin</artifactId>
				<version>1.8.0</version>
				<configuration>
					<updatePomFile>true</updatePomFile>
					<flattenMode>resolveCiFriendliesOnly</flattenMode>
				</configuration>
				<executions>
					<execution>
						<id>flatten</id>
						<phase>process-resources</phase>
						<goals>
							<goal>flatten</goal>
						</goals>
					</execution>
					<execution>
						<id>flatten.clean</id>
						<phase>clean</phase>
						<goals>
							<goal>clean</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.16.0</version>
				</plugin>

				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-jar-plugin</artifactId>
					<version>3.5.1</version>
				</plugin>

				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>3.6.0</version>
					<dependencies>
						<dependency>
							<groupId>me.fabriciorby</groupId>
							<artifactId>maven-surefire-junit5-tree-reporter</artifactId>
							<version>1.5.1</version>
						</dependency>
						<dependency>
							<!-- Surefire indirectly depends on an old version of ASM that doesn't support JDK 23. -->
							<groupId>org.ow2.asm</groupId>
							<artifactId>asm</artifactId>
							<version>9.10.1</version>
						</dependency>
					</dependencies>
					<configuration>
						<consoleOutputReporter>
							<disable>true</disable>
						</consoleOutputReporter>
						<statelessTestsetInfoReporter
								implementation="org.apache.maven.plugin.surefire.extensions.junit5.JUnit5StatelessTestsetInfoTreeReporter"/>
						<statelessTestsetReporter
								implementation="org.apache.maven.plugin.surefire.extensions.junit5.JUnit5Xml30StatelessReporter">
							<version>3.0.2</version>
							<usePhrasedFileName>false</usePhrasedFileName>
							<usePhrasedTestSuiteClassName>true</usePhrasedTestSuiteClassName>
							<usePhrasedTestCaseClassName>true</usePhrasedTestCaseClassName>
							<usePhrasedTestCaseMethodName>true</usePhrasedTestCaseMethodName>
						</statelessTestsetReporter>
						<systemProperties>
							<java.util.logging.config.file>${maven.multiModuleProjectDirectory}/test-logging.properties
							</java.util.logging.config.file>
						</systemProperties>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>