<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>eu.jbeernink.hypospray</groupId>
		<artifactId>discovery</artifactId>
		<version>${revision}</version>
	</parent>

	<groupId>eu.jbeernink.hypospray.discovery</groupId>
	<artifactId>eu.jbeernink.hypospray.discovery.annotated</artifactId>
	<version>${revision}</version>

	<dependencies>
		<dependency>
			<groupId>eu.jbeernink.hypospray</groupId>
			<artifactId>eu.jbeernink.hypospray.annotation</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>eu.jbeernink.hypospray</groupId>
			<artifactId>eu.jbeernink.hypospray.core</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>eu.jbeernink.hypospray.discovery</groupId>
			<artifactId>eu.jbeernink.hypospray.discovery.scanner</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>jakarta.enterprise</groupId>
			<artifactId>jakarta.enterprise.cdi-api</artifactId>
		</dependency>

		<dependency>
			<groupId>org.jspecify</groupId>
			<artifactId>jspecify</artifactId>
		</dependency>

		<dependency>
			<groupId>eu.jbeernink.hypospray.compile</groupId>
			<artifactId>eu.jbeernink.hypospray.compile.servicedescriptor</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>eu.jbeernink.hypospray.testing</groupId>
			<artifactId>extension</artifactId>
			<version>${project.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>eu.jbeernink.hypospray.testing</groupId>
			<artifactId>module</artifactId>
			<version>${project.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>eu.jbeernink.hypospray.testing</groupId>
			<artifactId>openmodule</artifactId>
			<version>${project.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>eu.jbeernink.hypospray.testing</groupId>
			<artifactId>automatic</artifactId>
			<version>${project.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>eu.jbeernink.hypospray.testing</groupId>
			<artifactId>nobeans</artifactId>
			<version>${project.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<scope>test</scope>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>eu.jbeernink.hypospray.compile</groupId>
							<artifactId>eu.jbeernink.hypospray.compile.servicedescriptor</artifactId>
							<version>${project.version}</version>
						</path>
					</annotationProcessorPaths>
					<annotationProcessors>
						<annotationProcessor>eu.jbeernink.hypospray.compile.servicedescriptor.ServiceDescriptorGenerator
						</annotationProcessor>
					</annotationProcessors>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.6.0</version>
				<configuration>
					<useModulePath>true</useModulePath>
					<statelessTestsetReporter
							implementation="org.apache.maven.plugin.surefire.extensions.junit5.JUnit5Xml30StatelessReporter">
						<disable>false</disable>
						<version>3.0</version>
						<usePhrasedFileName>false</usePhrasedFileName>
						<usePhrasedTestSuiteClassName>true</usePhrasedTestSuiteClassName>
						<usePhrasedTestCaseClassName>true</usePhrasedTestCaseClassName>
						<usePhrasedTestCaseMethodName>true</usePhrasedTestCaseMethodName>
					</statelessTestsetReporter>
					<consoleOutputReporter
							implementation="org.apache.maven.plugin.surefire.extensions.junit5.JUnit5ConsoleOutputReporter">
						<disable>false</disable>
						<encoding>UTF-8</encoding>
						<usePhrasedFileName>false</usePhrasedFileName>
					</consoleOutputReporter>
					<statelessTestsetInfoReporter
							implementation="org.apache.maven.plugin.surefire.extensions.junit5.JUnit5StatelessTestsetInfoReporter">
						<disable>false</disable>
						<usePhrasedFileName>false</usePhrasedFileName>
						<usePhrasedClassNameInRunning>true</usePhrasedClassNameInRunning>
						<usePhrasedClassNameInTestCaseSummary>true</usePhrasedClassNameInTestCaseSummary>
					</statelessTestsetInfoReporter>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>